/**
 * @file can_ids.h
 * @brief CAN ID definitions for Piper robot arm (V2 protocol)
 *
 * All CAN arbitration IDs used by the Piper arm protocol.
 * 11-bit standard CAN, big-endian byte order, 8-byte frames.
 */
#ifndef CPIPER_CAN_IDS_H
#define CPIPER_CAN_IDS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Feedback: arm → PC */
#define CAN_ID_ARM_STATUS_FEEDBACK           0x2A1
#define CAN_ID_ARM_END_POSE_FEEDBACK_1       0x2A2
#define CAN_ID_ARM_END_POSE_FEEDBACK_2       0x2A3
#define CAN_ID_ARM_END_POSE_FEEDBACK_3       0x2A4
#define CAN_ID_ARM_JOINT_FEEDBACK_12         0x2A5
#define CAN_ID_ARM_JOINT_FEEDBACK_34         0x2A6
#define CAN_ID_ARM_JOINT_FEEDBACK_56         0x2A7
#define CAN_ID_ARM_GRIPPER_FEEDBACK          0x2A8
#define CAN_ID_ARM_INFO_HIGH_SPD_FEEDBACK_1  0x251
#define CAN_ID_ARM_INFO_HIGH_SPD_FEEDBACK_2  0x252
#define CAN_ID_ARM_INFO_HIGH_SPD_FEEDBACK_3  0x253
#define CAN_ID_ARM_INFO_HIGH_SPD_FEEDBACK_4  0x254
#define CAN_ID_ARM_INFO_HIGH_SPD_FEEDBACK_5  0x255
#define CAN_ID_ARM_INFO_HIGH_SPD_FEEDBACK_6  0x256
#define CAN_ID_ARM_INFO_LOW_SPD_FEEDBACK_1   0x261
#define CAN_ID_ARM_INFO_LOW_SPD_FEEDBACK_2   0x262
#define CAN_ID_ARM_INFO_LOW_SPD_FEEDBACK_3   0x263
#define CAN_ID_ARM_INFO_LOW_SPD_FEEDBACK_4   0x264
#define CAN_ID_ARM_INFO_LOW_SPD_FEEDBACK_5   0x265
#define CAN_ID_ARM_INFO_LOW_SPD_FEEDBACK_6   0x266
#define CAN_ID_ARM_FIRMWARE_READ             0x4AF
#define CAN_ID_ARM_FEEDBACK_RESP_SET_INSTRUCTION           0x476
#define CAN_ID_ARM_FEEDBACK_CURRENT_MOTOR_ANGLE_LIMIT_MAX_SPD  0x473
#define CAN_ID_ARM_FEEDBACK_CURRENT_END_VEL_ACC_PARAM      0x478
#define CAN_ID_ARM_CRASH_PROTECTION_RATING_FEEDBACK        0x47B
#define CAN_ID_ARM_FEEDBACK_CURRENT_MOTOR_MAX_ACC_LIMIT    0x47C
#define CAN_ID_ARM_GRIPPER_TEACHING_PENDANT_PARAM_FEEDBACK 0x47E

/* Control: PC → arm */
#define CAN_ID_ARM_MOTION_CTRL_1             0x150
#define CAN_ID_ARM_MOTION_CTRL_2             0x151
#define CAN_ID_ARM_MOTION_CTRL_CARTESIAN_1   0x152
#define CAN_ID_ARM_MOTION_CTRL_CARTESIAN_2   0x153
#define CAN_ID_ARM_MOTION_CTRL_CARTESIAN_3   0x154
#define CAN_ID_ARM_JOINT_CTRL_12             0x155
#define CAN_ID_ARM_JOINT_CTRL_34             0x156
#define CAN_ID_ARM_JOINT_CTRL_56             0x157
#define CAN_ID_ARM_GRIPPER_CTRL              0x159
#define CAN_ID_ARM_JOINT_MIT_CTRL_1          0x15A
#define CAN_ID_ARM_JOINT_MIT_CTRL_2          0x15B
#define CAN_ID_ARM_JOINT_MIT_CTRL_3          0x15C
#define CAN_ID_ARM_JOINT_MIT_CTRL_4          0x15D
#define CAN_ID_ARM_JOINT_MIT_CTRL_5          0x15E
#define CAN_ID_ARM_JOINT_MIT_CTRL_6          0x15F
#define CAN_ID_ARM_MASTER_SLAVE_MODE_CONFIG  0x470
#define CAN_ID_ARM_MOTOR_ENABLE_DISABLE_CONFIG 0x471
#define CAN_ID_ARM_SEARCH_MOTOR_MAX_ANGLE_SPD  0x472
#define CAN_ID_ARM_MOTOR_ANGLE_LIMIT_MAX_SPD_SET 0x474
#define CAN_ID_ARM_JOINT_CONFIG              0x475
#define CAN_ID_ARM_INSTRUCTION_RESPONSE_CONFIG 0x477
#define CAN_ID_ARM_PARAM_ENQUIRY_AND_CONFIG  0x479
#define CAN_ID_ARM_END_VEL_ACC_PARAM_CONFIG  0x47A
#define CAN_ID_ARM_CRASH_PROTECTION_RATING_CONFIG 0x47D
#define CAN_ID_ARM_REQ_MASTER_ARM_HOME       0x176
#define CAN_ID_ARM_GRIPPER_TEACHING_PENDANT_PARAM_CONFIG 0x47F

#ifdef __cplusplus
}
#endif

#endif /* CPIPER_CAN_IDS_H */
